### PR TITLE
Added instructions for a chocolatey installation.

### PR DESCRIPTION
**Pull request by mikecole**

### CODE REVIEW

**Comment by dahlbyk** [comment]
Good change, but holding off until the package fixed.

**Comment by mikecole** [comment]
Is that the edit I current see out there from 5/13: https://chocolatey.org/packages/poshgit/0.5.1.20150209

If not, I can look at fixing the issue with the Chocolatey package.

**Comment by dahlbyk** [comment]
Already started on fix, just need to finish: #184

**Comment by mikecole** [comment]
:thumbsup:

**Comment by rkeithhill** [comment]
The README.md has changed a lot but I have added choco install instructions.  I'm closing this PR but please check the choco install instructions in the updated README.md.  Thanks!

**Pull request closed without merging**
