### PR TITLE
Add a GitHub workflow

### PR DESCRIPTION
**Pull request by dscho**
GitHub workflows provide the fastest and most convenient way to perform Continuous Testing on Windows, macOS and Linux.

Note: currently, there are a few test failures (not introduced by this PR!) that we will have to resolve before this becomes useful.

### CODE REVIEW

**Comment by dscho** [comment]
I fear that the test failures ([some of which have been reported before](https://github.com/dahlbyk/posh-git/pull/864#issuecomment-875378865)) are not new, and I fear it is necessary to fix them. However, I am clueless how the `script:`-scoped functions are seemingly no longer visible from the module functions, I am not a PowerShell expert. Help?

**Comment by dahlbyk** [comment]
Thanks for this! I had been meaning to get off Travis. Entering the final week of the course I've been teaching, so expect more attention from me soon.

**Comment by dahlbyk** [comment]
Will troubleshoot failures in a different PR.

**Comment by dscho** [comment]
> Will troubleshoot failures in a different PR.

Thank you! Could you let me know which PR once it is opened?

**Pull request merged**
