### PR TITLE
Guess agent location if not on path

### PR DESCRIPTION
**Pull request by theaquamarine**
Implements #114 for ssh-agent and pageant

### CODE REVIEW

**Comment by giggio** [comment]
@dahlbyk Do you have an idea of when you plan to work on this?

**Comment by rpavlik** [comment]
Will this get merged soon? After adding aliases to my profile as a workaround:

```powershell
# Aliases to find ssh-agent/ssh-add to quiet down posh-git - http://stackoverflow.com/a/24368751/265522
Set-Alias ssh-agent "${env:ProgramFiles(x86)}\git\bin\ssh-agent.exe"
Set-Alias ssh-add "${env:ProgramFiles(x86)}\git\bin\ssh-add.exe"
```

posh itself seems to start a lot faster now - was taking several seconds before with that error message.

**Comment by giggio** [comment]
This PR will have its first birthday soon.

**Comment by giggio** [comment]
Tks!

**Pull request merged**
