### PR TITLE
Only default home dir abbreviation to $true on Linux/macOS

### PR DESCRIPTION
**Pull request by rkeithhill**
If enabled, always substitute ~ for the home dir path on all OSs.

Address issue brought up in #746

### CODE REVIEW

**Comment by rkeithhill** [comment]
@dahlbyk Well, this looks a little odd now:
image

**Comment by dahlbyk** [comment]
> @dahlbyk Well, this looks a little odd now:
> 
> image
> 
> Can we change that separator character or maybe just get rid of it?

The `~` was introduced in 1ed6d4d3c26059c5b0abbd33708dde2be70ad8f2 due to a Console2 bug that's either long fixed or likely irrelevant—and it's customizable. Let's change to a `-` by default, or maybe `>` to roughly mirror what's visible in the prompt?

**Review by dahlbyk — APPROVED** [review]
Leaving open in case you want to tack on the `~` change. Otherwise feel free to merge.

**Comment by rkeithhill** [comment]
Here's what a `>` looks like:

image

image

vs a `-`

image

image

I dunno.  Having `>` in the title bar seems a bit weird to me while `-` seems more "titlebar like".

**Comment by dahlbyk** [comment]
> Having `>` in the title bar seems a bit weird to me while `-` seems more "titlebar like".

Concur. Let's go with `-`.

**Pull request merged**
