### PR TITLE
Add a module manifest

### LINKED ISSUE #224: Start-SSHAgent missing in v0.5.0.2015
After a clean install with PowershellGet of version 0.5.0.2015 i receive the error below after running the install.ps1 file.  The install appended the following to my profile:

````powershell

# Load posh-git example profile
. 'C:\Program Files\WindowsPowerShell\Modules\posh-git\0.5.0.2015\profile.example.ps1'
````

````powershell
Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.

Start-SshAgent : The term 'Start-SshAgent' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\Program Files\WindowsPowerShell\Modules\posh-git\0.5.0.2015\profile.example.ps1:25 char:1
+ Start-SshAgent -Quiet
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Start-SshAgent:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

C:\jbtemp\ps> get-command -module posh-git

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-AliasPattern                                   0.5.0.2015 posh-git
Function        Get-GitDirectory                                   0.5.0.2015 posh-git
Function        Get-GitStatus                                      0.5.0.2015 posh-git
Function        Invoke-NullCoalescing                              0.5.0.2015 posh-git
Function        TabExpansion                                       0.5.0.2015 posh-git
Function        tgit                                               0.5.0.2015 posh-git
Function        Update-AllBranches                                 0.5.0.2015 posh-git
Function        Write-GitStatus                                    0.5.0.2015 posh-git
Function        Write-Prompt                                       0.5.0.2015 posh-git
Function        Write-VcsStatus                                    0.5.0.2015 posh-git


C:\jbtemp\ps> get-module posh-git

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.5.0.2015 posh-git                            {Get-AliasPattern, Get-GitDirectory, Get-GitStatus, Invoke...
````

### PR DESCRIPTION
**Pull request by theaquamarine**
Providing a manifest should prevent any issues with exports occurring in the future. This will use the exports specified in posh-git.psm1 as discussed in #207, which should fix #224.

### CODE REVIEW

**Comment by svmastersamurai** [comment]
:+1: Would love to get my team on this module without having to make modifications manually :)

**Comment by dahlbyk** [comment]
>  Binary file not shown. 

It's likely the manifest is encoded as UTF-16. Can you reencode as UTF-8 so we can see the diff?

**Comment by theaquamarine** [comment]
Done. Thanks, Visual Studio!

**Comment by dahlbyk** [comment]
:sparkles:

**Comment by shiftkey** [comment]
Just a heads up - this change makes Posh-Git incompatible with users who are still running PowerShell v2 - `RootModule` is v3-specific, but also required to make it function as expected.

Was this intentional? Would you like me to log an issue about it?

**Comment by Haacked** [comment]
Hmm, based on https://github.com/dahlbyk/posh-git/pull/186 it looks like this was intentional. :cry:

**Comment by dahlbyk** [comment]
Also: https://github.com/dahlbyk/posh-git/issues/163

@shiftkey @Haacked do you have a sense how many GitHub Desktop users are still on PowerShell 2.0? PowerShell 3 has been out for 3.5 years now. :frowning:

**Comment by Haacked** [comment]
> @shiftkey @Haacked do you have a sense how many GitHub Desktop users are still on PowerShell 2.0? PowerShell 3 has been out for 3.5 years now.

Unfortunately this is not something we directly track today.

What we do know is that half of our users are on Windows 7, which comes with PowerShell 2.0 by default. I don't think Windows Update upgrades PowerShell, does it? So I have to assume that most people on Win7 are still on PS 2.0 because people never upgrade. http://blog.codinghorror.com/the-power-of-defaults/

**Comment by dahlbyk** [comment]
That would be useful telemetry to have!

If deprecating PS 2.0 is premature for your uses, we'll need to come up with a plan to not hold back the project (more than my neglect is already :imp:) while preserving what support we can going forward.

------

So @shiftkey what exactly is the problem with adding this `psd1`?

**Comment by shiftkey** [comment]
@dahlbyk the error message you see when launching Posh Git under PowerShell v2 kinda sums it up:

> Import-Module : The 'C:\path\to\posh-git.psd1' module cannot be imported because its manifest contains one or more members that are not valid. The valid manifest members are ('ModuleToProcess', 'NestedModules', 'GUID', 'Author', 'CompanyName', 'Copyright', 'ModuleVersion', 'Description', 'PowerShellVersion', 'PowerShellHostName', 'PowerShellHostVersion', 'CLRVersion', 'DotNetFrameworkVersion', 'ProcessorArchitecture', 'RequiredModules', 'TypesToProcess', 'FormatsToProcess', 'ScriptsToProcess', 'PrivateData', 'RequiredAssemblies', 'ModuleList', 'FileList', 'FunctionsToExport', 'VariablesToExport', 'AliasesToExport', 'CmdletsToExport'). **Remove the members that are not valid ('RootModule'), then try to import the module again.**

However you cannot just remove `RootModule` as other parts of the module seem to depend on this.

**Comment by dahlbyk** [comment]
Can you `Import-Module C:\path\to\posh-git.psm1` directly instead?

**Comment by theaquamarine** [comment]
`RootModule` is an alias for `ModuleToProcess` which existed in v2, so switching to that will function identically in v3+ and work in v2, Swapping seems an easy solution, since we gain nothing breaking compatibility here.
https://technet.microsoft.com/en-gb/library/hh849709.aspx

**Comment by shiftkey** [comment]
> Can you Import-Module `C:\path\to\posh-git.psm1` directly instead?

No errors reported against `master`, but the prompt isn't enhanced either:

```
PS C:\Users\shiftkey\Documents\GitHub\posh-git> Import-Module .\posh-git.psm1
WARNING: posh-git support for PowerShell 2.0 is deprecated; you have version 2.0.
To download version 3.0, please visit https://www.microsoft.com/en-us/download/details.aspx?id=34595
For more information and to discuss this, please visit https://github.com/dahlbyk/posh-git/issues/163
To suppress this warning, change your profile to include 'Import-Module posh-git -Args $true'.
```

**Pull request merged**
