### PR TITLE
Revert #489

### PR DESCRIPTION
**Pull request by dahlbyk**
https://github.com/dahlbyk/posh-git/pull/489 accidentally brought all of `develop` into `master`. That's what I get for being lazy and trying to do everything from GitHub dot com. 😒

### CODE REVIEW

**Comment by rkeithhill** [comment]
But I thought #489 merged `master` down to `develop` instead of the other way around?

**Comment by dahlbyk** [comment]
> But I thought #489 merged master down to develop instead of the other way around?

It did, but resolving the conflict online created https://github.com/dahlbyk/posh-git/pull/489/commits/79770b8ed5fe8b065483d6433896fbc00d3fc9af: "Merge branch 'develop' into master". Oops!

**Comment by rkeithhill** [comment]
Doh!

**Comment by dahlbyk** [comment]
Blah. So merging `master` into `develop` now includes this change, undoing all our work. Reverting the revert does work, but essentially discards the individual commits for `blame` purposes.

So.... I'm going to `--force` `master` back pre-#489 and try this all again. 👿

**Pull request merged**
