### PR TITLE
Add show remote name

### PR DESCRIPTION
**Pull request by marckassay**
This PR resolves feature request #781.

The updated README.md needs to have the following image added with the name of 'PromptShowRemoteName.png' to GitHub:
PromptShowRemoteName

### CODE REVIEW

**Comment by dahlbyk** [comment]
With your permission, I'd like to reopen and merge this. Busy summer. 😢

**Comment by dahlbyk** [comment]
> The updated README.md needs to have the following image added with the name of 'PromptShowRemoteName.png' to GitHub:
> PromptShowRemoteName

Added.

**Comment by marckassay** [comment]
As an alternative PR to this one, I recommended PR #914.

**Comment by dahlbyk** [comment]
Closing in favor of #908. Will try to review this evening. Thanks!

**Comment by marckassay** [comment]
Closing in favor of PR #914

**Comment by dahlbyk** [comment]
🤦‍♂️ meant to close

**Pull request closed without merging**
