### PR TITLE
Prep CHANGELOG for 1.0.0-beta4

### PR DESCRIPTION
**Pull request by rkeithhill**

### CODE REVIEW

**Comment by rkeithhill** [comment]
IMO beta4 is ready to go. Just merge this PR in and publish.  You might think about looking at and merging PR #698 but at this point, I'd just like to get beta4 out the door.  :-)

**Comment by vchirikov** [comment]
@rkeithhill when beta4 will be published? I mean we all want to get switch/restore autocomplete 👏

**Comment by rkeithhill** [comment]
It's ready to go IMO.  Waiting on @dahlbyk to do the publish.

**Comment by dahlbyk** [comment]
I have been putting this off for a variety of reasons, but I _will_ get this out this month.

**Comment by dahlbyk** [comment]
> I _will_ get this out this month.

Happy Pi Day (CDT)!

https://github.com/dahlbyk/posh-git/releases/tag/v1.0.0-beta4

**Pull request merged**
