### PR TITLE
Normalize line endings

### LINKED ISSUE #334: LF normalization disabled in .gitattributes
I see this in .gitattributes:
```
# Disable LF normalization for all files
* -text
```
Why do we do this?  When I git clone the repo on Linux and test/edit files, the line endings are screwed up in VI.

### PR DESCRIPTION
**Pull request by dahlbyk**
We don't need to merge this before we ship 0.7 (#327), but this will close #334.

There is a good chance GitHub will refuse to merge the remaining open PRs. To resolve, we will want to set `git config --global merge.renormalize true`, ensure `master` is up-to-date, and then either:

1. `git rebase master` to replay changes after the normalization
2. `git merge master` to bring in these changes

### CODE REVIEW

**Comment by rkeithhill** [comment]
> There is a good chance GitHub will refuse to merge the remaining open PRs

That's good incentive to accept / reject as PRs as makes sense for 0.7.0.  :-)

**Comment by dahlbyk** [comment]
We can also include #341 in this PR, when the time comes.

**Comment by dahlbyk** [comment]
Well crap, should have waited for build to run: https://ci.appveyor.com/project/dahlbyk/posh-git/build/0.7.158. Tests aren't happy about the line ending normalization.

**Comment by rkeithhill** [comment]
I can fix that tonight, if you want.

**Pull request merged**
