### PR TITLE
Move appveyor build to Pester 4

### LINKED ISSUE #485: Upgrade to Pester 4
Build is breaking at least due to https://github.com/pester/Pester/pull/859 ([example](https://ci.appveyor.com/project/dahlbyk/posh-git/build/0.7.335#L187)).

Workaround: https://github.com/dahlbyk/posh-git/pull/484/commits/3aa739b3911677e29e564137ff0a7dcce3f95007

### PR DESCRIPTION
**Pull request by rkeithhill**
Fix #485

### CODE REVIEW

**Comment by dahlbyk** [comment]
Is there any reason this change wouldn't work for `master`, too?

**Comment by rkeithhill** [comment]
None that I can think of.

**Comment by dahlbyk** [comment]
If only PRs could be retargeted... 😞 

Care to open another PR into `master`? 😀

**Comment by rkeithhill** [comment]
Done.

**Pull request merged**
