### PR TITLE
Put 'CACHE ERROR' in prompt when cache returns failure.

### PR DESCRIPTION
**Pull request by cmarcusreid**
Follow-up from https://github.com/dahlbyk/posh-git/issues/755

image

This diff is a bit unfortunate; the only new bit is the leading if block. The rest was indented in the new else block.

### CODE REVIEW

**Comment by rkeithhill** [comment]
Fortunately, you can diff this in VSCode with the GitHub Pull Requests extension.  And because VSCode diffs allow you to ignore whitespace, this diff simplifies to:

image

**Comment by cmarcusreid** [comment]
TIL! Thanks!

**Comment by rkeithhill** [comment]
I really wish GitHub would offer the option to ignore whitespace changes.  This is one area where Bitbucket has a leg up on GH.

**Comment by rkeithhill** [comment]
Thanks for the PR!  I've asked the other Keith to review it before merging it.

**Comment by dahlbyk** [comment]
Thanks for the fix, @cmarcusreid!

> I really wish GitHub would offer the option to ignore whitespace changes in diffs. This is one area where Bitbucket has a leg up on GH.

You have been able to add `?w=1` for years, but it has been in the UI for a while, too.

Screenshot_20200407-212532

**Comment by rkeithhill** [comment]
Thanks for pointing that out! That has been bugging me for a while. I was looking in the wrong place - in the `...` menu to the right of the `Viewed` button.

**Pull request merged**
