### PR TITLE
Fixes Get-SshPath from returning an emtpy value

### PR DESCRIPTION
**Pull request by motowilliams**
Fixes issue #268

### CODE REVIEW

**Comment by dahlbyk** [comment]
Interesting...are you getting an error other than:

```
C:\Dev\OSS\posh-git [master ≡]> Resolve-Path (Join-Path $home ".ssh\$File")
Resolve-Path : Cannot find path 'C:\Users\Keith\.ssh\id_rsa' because it does not exist.
At line:1 char:1
+ Resolve-Path (Join-Path $home ".ssh\$File")
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Keith\.ssh\id_rsa:String) [Resolve-Path], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand
```
While testing this myself, I stumbled on a related error:

```
Cannot overwrite variable HOME because it is read-only or constant.
At line:1 char:1
+ $home = Resolve-Path (Invoke-NullCoalescing $Env:HOME ~)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (HOME:String) [], SessionStateUnauthorizedAccessException
    + FullyQualifiedErrorId : VariableNotWritable
```

We should stop trying to set `$HOME`, but I wonder if that's part of your problem?

**Comment by theaquamarine** [comment]
I was just wondering how that `$home` bit was working, since it's a read-only variable. It's also an automatic variable, so wouldn't it be a better option in line 330? I'm not sure about `$env:Home`, but `~` is usually a bad plan- it's provider specific and most providers don't implement it, whereas $home always refers to the user's home folder.

Isn't the returning an empty path a function of the ErrorAction and stream redirection rather than `Join-Path` vs `[io.path]::combine`? Returning an empty path seems like a reasonable thing to do if it can't find the file specified.

I like the not hard coding backslash as path separator.

**Comment by motowilliams** [comment]
Yes I was also getting the writing to home error but I was also getting the error with that Join-Path.

**Comment by dahlbyk** [comment]
> I was also getting the error with that Join-Path.

What's the error message? Just trying to understand the problem - the `Join-Path` is pretty straightforward, not sure why its behavior would have changed in newer PowerShell/Windows.

**Comment by rkeithhill** [comment]
Um, yeah $Home is a built-in, readonly PowerShell variable. There should be no need to use $env:Home or `~` and if you never use `~` you never need to resolve the path (to expand `~`).  Fixed by PR #325

**Comment by dahlbyk** [comment]
> Um, yeah `$Home` is a built-in, readonly PowerShell variable. There should be no need to use `$env:Home` or `~` and if you never use `~` you never need to resolve the path (to expand `~`).

See https://github.com/dahlbyk/posh-git/issues/153 for some background on use of `%HOME%`.

**Comment by rkeithhill** [comment]
The `%HOME%` environment variable is different from the PowerShell `$Home` variable although both should specify the same path.   Or is the issue not how you come up with the user's home dir and something else?

**Comment by dahlbyk** [comment]
It may have changed in newer versions, but I think the point of using `%HOME%` was to align with Git for Windows and the MSYS utilities that depend on the same. Basically, if `%HOME%` doesn't match `$Home` there could be unexpected behavior.

**Pull request closed without merging**
