### PR TITLE
Release v0.7.0

### LINKED ISSUE #353: Next Release Date?
Any estimated time for the next release?

### PR DESCRIPTION
**Pull request by dahlbyk**
* [x] Bump PowerShellGet version (#378)
* [x] Bump Chocolatey version
* [x] Finalize `CHANGELOG.md` https://github.com/dahlbyk/posh-git/pull/402
* [x] Tag v0.7.0
* [x] Push to Chocolatey
* [x] Push to PowerShell Gallery

Closes #353

### CODE REVIEW

**Comment by dahlbyk** [comment]
@rkeithhill can you take a final pass through the change log, since you've been keeping it current? Everything else in [this Milestone](https://github.com/dahlbyk/posh-git/milestone/1) is marked done. Are we missing anything?

**Comment by rkeithhill** [comment]
You added Test-PoshGitInProfile, right?  Is that supposed to be exported from the module?  

I'm working on a PR for the CHANGELOG right now.

**Comment by rkeithhill** [comment]
Ugh, looks like the EOL normalization messed up the Pester tests. I'll fix these tonight.

**Comment by dahlbyk** [comment]
> You added Test-PoshGitInProfile, right? Is that supposed to be exported from the module?

You added in #361 to support `Add-PoshGitToProfile`. I don't think it needs to be exported.

> Ugh, looks like the EOL normalization messed up the Pester tests. I'll fix these tonight.

Fixed by https://github.com/dahlbyk/posh-git/pull/401.

**Comment by rkeithhill** [comment]
Cool.  Thanks.

**Comment by rkeithhill** [comment]
> You added in #361 to support Add-PoshGitToProfile. I don't think it needs to be exported.

Sorry, What I was actually thinking of was `Remove-PoshGitFromProfile`.  I thought you had added such a command at one point but I can't find it.  So ... nevermind.

**Comment by dahlbyk** [comment]
> Sorry, What I was actually thinking of was `Remove-PoshGitFromProfile`. I thought you had added such a command at one point but I can't find it. So ... nevermind.

I had introduced it with #239, but pulled it out to keep the PR focused on Chocolatey. That commit now lives in https://github.com/dahlbyk/posh-git/compare/remove-from-profile, ready to be revisited if we deem it useful.

**Comment by rkeithhill** [comment]
@dahlbyk  I think we are getting close.  I don't have anything else (issues/PRs).  The CHANGELOG.md is up-to-date AFAIK.  That said, I fully expect that after this is released into the wild, we'll be doing a 0.7.1 within weeks to a month.  Just the way it goes with the amount of code change we've made.

**Comment by dahlbyk** [comment]
> That said, I fully expect that after this is released into the wild, we'll be doing a 0.7.1 within weeks to a month. Just the way it goes with the amount of code change we've made.

👍 

My wife's out of town this week, so off hours are limited, but I'll try to review #402 soon.

**Comment by rkeithhill** [comment]
No problem.  I set a tentative release date of 2/14 - our Valentine's gift to the posh-git user community.  :-)

**Comment by rkeithhill** [comment]
@dahlbyk I think this release is ready to cut loose.

**Comment by dahlbyk** [comment]
> - [x] Tag v0.7.0
> - [x] Push to Chocolatey
> - [x] Push to PowerShell Gallery

Not quite as smooth as one might have hoped, but the release is out on [Chocolatey](https://chocolatey.org/packages/poshgit/0.7.0) and [PowerShell Gallery](https://www.powershellgallery.com/packages/posh-git/0.7.0).

`Publish-Module` apparently won't find modules that don't live in a folder of the same name:

```
C:\Dev\OSS\posh-git [release-v0.7.0 ≡]> publish-module -Path .\src  -NuGetApiKey 'deadbeef-dead-beef-dead-beefdeadbeef'
publish-module : The specified module with path '.\src' was not published because no valid module was found with that path.
At line:1 char:1
+ publish-module -Path .\src  -NuGetApiKey 'deadbeef-dead-beef-dead-bee ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (.\src:String) [Publish-Module], ArgumentException
    + FullyQualifiedErrorId : InvalidModulePathToPublish,Publish-Module
```

**Comment by rkeithhill** [comment]
Ah, that's why I typically have a "build release" stop that copies the contents of src into a `.release\<module-name>` folder and I publish from there.   Need to get back to work on PlasterBuild.  :-)

**Comment by dahlbyk** [comment]
> Ah, that's why I typically have a "build release" stop that copies the contents of src into a `.release\<module-name>` folder and I publish from there. Need to get back to work on PlasterBuild. :-)

I am content to discard the last two commits, if you think that's a better approach. The other benefit of using `posh-git/` instead of `src/` is that the hack from #392 could be reverted.

**Comment by dahlbyk** [comment]
@Haacked @shiftkey if you want to start pulling an update into GitHub Desktop, I'd use [v0.7.0](https://github.com/dahlbyk/posh-git/commits/v0.7.0). I'm not certain we'll keep the last few commits in this branch. Let me know if you have any issues!

**Comment by dahlbyk** [comment]
> > Ah, that's why I typically have a "build release" stop that copies the contents of src into a `.release\<module-name>` folder and I publish from there. Need to get back to work on PlasterBuild. :-)
>
> I am content to discard the last two commits, if you think that's a better approach. The other benefit of using `posh-git/` instead of `src/` is that the hack from #392 could be reverted.

@rkeithhill thoughts? I'd like to merge this to close the loop on v0.7.0, but am ambivalent between `posh-git/` and `src/`. The former seems to have a couple advantages, and I'm not sure what a "release" process would do other than copy `src/` elsewhere.

**Comment by rkeithhill** [comment]
The build pipeline I'm about to start working on again in PlasterBuild has several additional steps that necessitate creating some sort of "output" dir whether that's called `Release`, `.release`,  or `out`.  

The current thinking on the build pipeline is this:
```
Init, Clean, BeforeBuild, StageFiles, Analyze, Sign, AfterBuild, Test, BuildHelp, GenerateFileCatalog, Install, Publish
```
Not all of those steps are required.  Script signing is optional as-is using the markdown help generator and generating file catalogs.  And the `Install` and `Publish` build steps are primarily meant to be invoked manually.  Although I believe the PowerShell team wants module authors to start providing generating a file catalog.

Not to mention `~\GitHub\dahlbyk\posh-git\posh-git` just looks weird to me.  :-)

**Comment by dahlbyk** [comment]
:ok: dropped the commits to move from `src/` to `posh-git`. Those changes, should wish to restore them:
[0001-Move-module-files-from-src-into-directory-of-same-na.patch](https://github.com/dahlbyk/posh-git/files/782334/0001-Move-module-files-from-src-into-directory-of-same-na.patch.txt)
[0002-Revert-src-check-in-PSModulePath.patch](https://github.com/dahlbyk/posh-git/files/782335/0002-Revert-src-check-in-PSModulePath.patch.txt)

**Pull request merged**
