### PR TITLE
Add Visual Studio pssproj & solution

### PR DESCRIPTION
**Pull request by theaquamarine**
Sets it up so poshtools is ready to go with tests loaded.

### CODE REVIEW

**Comment by rkeithhill** [comment]
So, why do we need Visual Studio and PoshTools (Windows only)? There isn't a build per-se for this module yet.  We just a need to run Pester tests. This seems a bit sledgehammer-ish.  :-)

**Comment by theaquamarine** [comment]
Mostly just because I find it useful, so others might. I figure anything that might make contributing for someone new is a plus, though I suppose the niche of people who use VS, have poshtools and don't know how to use Pester any other way is going to be fairly small.

**Comment by rkeithhill** [comment]
Yeah, given that the push here is to support PS Core which is cross-platform, it would be nice to avoid using "Windows-only" tools like Visual Studio.   Also, the intersection of that Venn diagram you mention, is likely very small.  :-)  

If we really want to do this, I think it would be better to put the two VS specific files in a subdir like `.vs`.

**Comment by dahlbyk** [comment]
I'm ambivalent on this. On one hand, including these files may reduce barriers to contribution for folks familiar with the VS tools, without interfering with those who won't use them. On the other hand, the `.pssproj` seems somewhat likely to get out-of-date if it's not actively used by most contributors, leading to frustration for would-be contributors if things don't Just Work™️.

What if we just ignored `*.pssproj` and `*.sln` along with `.vs/`?

**Comment by rkeithhill** [comment]
The suggested solution is to create another PR to add *.pssproj, *.sln and .vs/ to the .gitignore file.

**Pull request closed without merging**
