### PR TITLE
Add 'push' to the list of commands to handle tab tag completion

### PR DESCRIPTION
**Pull request by joshgo**
Hi Keith, First time using posh-git. I'm not a powershell guy, but I was able to follow the code and make the minor modification. Hopefully, that's all that is needed. I added this because tab completion for tags exist in Git Bash when using "git push".

### CODE REVIEW

**Comment by dahlbyk** [comment]
We handle `push` a little differently because `<origin> is required before the branch/tag. Try [here](https://github.com/joshgo/posh-git/blob/e415a03bd92d26a23e11f2b9a898ec8707c26bf3/GitTabExpansion.ps1#L233-L235) instead?

**Comment by joshgo** [comment]
> ` is required before the branch/tag
Single quote/accent ? Apologies, I'm not sure what you are saying.

I looked at line 233-235 as per your suggestion, that doesn't get invoked when I type:

`git push origin {tab-key}`

[Line 239-241](https://github.com/joshgo/posh-git/blob/e415a03bd92d26a23e11f2b9a898ec8707c26bf3/GitTabExpansion.ps1#L239-L241) is what gets invoked.

If I add a call to `gitTags`, it works. Without changing the regex variable name, the call would be: `gitTags matches['branch']`. I don't like that it says 'branch', it's a little misleading...but works.

**Comment by dahlbyk** [comment]
> Line 239-241 is what gets invoked.

Oh, right you are. 233-235 is specifically for `git push foo bar:<tab>`.

> I don't like that it says 'branch', it's a little misleading...but works.

Agreed. Let's change that to `ref`.

**Comment by joshgo** [comment]
Changes are done. Thanks for feedback.

**Comment by dahlbyk** [comment]
:sparkles: :bow:

**Pull request merged**
